import { Serie } from './Serie.js';
export var series = [
    new Serie(1, "Breaking Bad", "AMC", 5, "Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer", "https://www.amc.com/shows/breaking-bad", "https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@.V1_FMjpg_UX1000.jpg"),
    new Serie(2, "Orange Is the New Black", "Netflix", 6, "The series begins revolving around Piper Chapman, a woman in her thirties living in New York City who is sentenced to 15 months in Litchfield Penitentiary", "https://www.netflix.com/co/title/70242311", "https://akns-images.eonline.com/eol_images/Entire_Site/201869/rs_634x939-180709061638-634-oitnb-s6.ch.070918.jpg?fit=around%7C634:939&output-quality=90&crop=634:939;center,top"),
    new Serie(3, "Game of Thrones", "HBO", 7, "Set on the fictional continents of Westeros and Essos, Game of Thrones has a large ensemble cast and follows several story arcs throughout the course of the show.", "https://www.hbo.com/game-of-thrones", "https://assets-prd.ignimgs.com/2022/01/14/gameofthrones-allseasons-sq-1642120207458.jpg"),
    new Serie(4, "The Big Bang Theory", "CBS", 12, "Leonard and Sheldon are brilliant physicists—geniuses in the laboratory but socially challenged everywhere else...", "https://www.cbs.com/shows/big_bang_theory/about/", "https://img.posterstore.com/zoom/wb0174-8thebigbangtheory-thegroup50x70.jpg"),
    new Serie(5, "Sherlock", "BBC", 4, "Sherlock depicts consulting detective Sherlock Holmes solving various mysteries in modern-day London.", "https://www.bbc.co.uk/programmes/b018ttws", "https://m.media-amazon.com/images/I/51OHBzwfZtL.AC_UF894,1000_QL80.jpg"),
    new Serie(6, "A Very English Scandal", "BBC", 2, "A fact-based three-part British television comedy-drama miniseries...", "https://www.bbc.co.uk/programmes/p065smy4", "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p15526450_b_v13_ao.jpg"),
];
